applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  artifactory-ha.serviceAccount.name:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
  artifactory-ha.postgresql.postgresPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
        includeSymbols: False  # Default is False
        base64: True           # Default is True
  artifactory-ha.artifactory.masterKey:
    title: 'Artifactory requires a unique master key'
    description: 'You can generate one with the command: openssl rand -hex 32'
    default: 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'
    type: string
  artifactory-ha.artifactory.image.repository:
    type: string
    default: gcr.io/jfrog-gc-mp/jfrog/artifactory-pro
    x-google-marketplace:
      type: IMAGE
  artifactory-ha.artifactory.persistence.storageClass:
    title: Storage class for Artifactory nodes, SSD storage recommended.
    type: string
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD
  artifactory-ha.artifactory.persistence.size:
    title: Disk allocation to Artifactory nodes
    type: string
    default: "200Gi"
  artifactory-ha.artifactory.primary.resources.requests.cpu:
    title: CPU units for primary node
    type: string
    default: "100m"
  artifactory-ha.artifactory.primary.resources.requests.memory:
    title: Memory for primary node
    type: string
    default: "512M"
  artifactory-ha.artifactory.primary.resources.limits.cpu:
    title: CPU units for primary node (limit)
    type: string
    default: "8"
  artifactory-ha.artifactory.node.replicaCount:
    type: integer
    title: 'Artifactory Member Node count'
    description: 'Artifactory Member Node count (1 Primary + 2 Member = 3 Node Cluster)'
    default: 2
    minimum: 1
    maximum: 10
  artifactory-ha.artifactory.primary.resources.limits.memory:
    title: Memory for primary node (limit)
    type: string
    default: "512G"
  artifactory-ha.artifactory.node.resources.requests.cpu:
    title: CPU units per node
    type: string
    default: "100m"
  artifactory-ha.artifactory.node.resources.requests.memory:
    title: Memory per node
    type: string
    default: "512M"
  artifactory-ha.artifactory.node.resources.limits.cpu:
    title: CPU units per node (limit)
    type: string
    default: "8"
  artifactory-ha.artifactory.node.resources.limits.memory:
    title: Memory per node (limit)
    type: string
    default: "512G"
  artifactory-ha.nginx.image.repository:
    type: string
    default: gcr.io/jfrog-gc-mp/jfrog/nginx-artifactory-pro
    x-google-marketplace:
      type: IMAGE
  artifactory-ha.nginx.service.type:
    title: 'Nginx Service Type'
    description: 'Nginx Service Type'
    default: 'LoadBalancer'
    type: string
required:
- name
- namespace
- artifactory-ha.serviceAccount.name
- artifactory-ha.postgresql.postgresPassword
- artifactory-ha.artifactory.masterKey
- artifactory-ha.artifactory.node.replicaCount
- artifactory-ha.artifactory.image.repository
- artifactory-ha.artifactory.persistence.storageClass
- artifactory-ha.artifactory.persistence.size
- artifactory-ha.artifactory.primary.resources.requests.cpu
- artifactory-ha.artifactory.primary.resources.requests.memory
- artifactory-ha.artifactory.primary.resources.limits.cpu
- artifactory-ha.artifactory.primary.resources.limits.memory
- artifactory-ha.artifactory.node.resources.requests.cpu
- artifactory-ha.artifactory.node.resources.requests.memory
- artifactory-ha.artifactory.node.resources.limits.cpu
- artifactory-ha.artifactory.node.resources.limits.memory
- artifactory-ha.nginx.image.repository
- artifactory-ha.nginx.service.type
