FROM docker.bintray.io/jfrog/artifactory-pro:6.13.1

ADD sources /third-party-oss/sources/
ADD THIRD-PARTY-LICENSES /third-party-oss/
ADD Dockerfile.artifactory /docker/artifactory-pro/Dockerfile.GKE
