FROM gcr.io/soldev-dev/nginx-jfrog-artifactory:7.0.0-m187

ADD sources /third-party-oss/sources/
ADD THIRD-PARTY-LICENSES /third-party-oss/
ADD Dockerfile.nginx /docker/artifactory-pro/Dockerfile.GKE
