FROM gcr.io/soldev-dev/jfrog-artifactory/artifactory-jcr:6.x.feature.RTFACT.19960_for6-104


ADD sources /third-party-oss/sources/
ADD THIRD-PARTY-LICENSES /third-party-oss/
ADD Dockerfile.artifactory /docker/artifactory-pro/Dockerfile.GKE
