FROM gcr.io/jfrog-gc-mp/jfrog-artifactory/nginx-artifactory-pro:7.0.0-m664

ADD sources /third-party-oss/sources/
ADD THIRD-PARTY-LICENSES /third-party-oss/
ADD Dockerfile.nginx /docker/artifactory-pro/Dockerfile.GKE
