FROM docker.bintray.io/jfrog/artifactory-pro:7.11.5

ADD sources /third-party-oss/sources/
ADD THIRD-PARTY-LICENSES /third-party-oss/
ADD Dockerfile.artifactory /docker/artifactory-pro/Dockerfile.GKE
