ARG TAG

FROM releases-docker.jfrog.io/jfrog/xray-persist:${TAG}
ADD THIRD-PARTY-LICENSES /third-party-oss/
ADD Dockerfile.xray-persist /docker/xray/Dockerfile.GKE
COPY xray.default /opt/jfrog/xray/app/bin
