dependencies:
- name: artifactory-ha
  version: 2.5.0
  repository: https://charts.jfrog.io
- name: xray
  version: 3.3.2
  repository:  https://partnership.jfrog.io/artifactory/artifactory7-partnership-helm/
  condition: xray.enabled